language: python

notifications:
  email: jindaxiang@163.com

dist: xenial
sudo: required

python:
- "3.6.1"
- "3.6.5"
- "3.7.3"
- "3.7.5"
- "3.8.1"

install:
- pip install -r requirements.txt
- pip install codecov

script: coverage run --source=akshare -m pytest && coverage report

after_success:
- codecov

branches:
  only:
  - master
