os: linux
dist: xenial
language: python

python:
- "3.6.5"
- "3.7.5"
- "3.8.1"

branches:
  only:
  - master

install:
- pip install -r requirements.txt
- pip install codecov flake8

before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

script: coverage run --source=akshare -m pytest && coverage report

after_success:
- codecov

notifications:
  email: jindaxiang@163.com
